
% Definisco ISS

Create Spacecraft ISS;

GMAT ISS.DateFormat = UTCGregorian;
GMAT ISS.Epoch = '03 Jun 2026 23:13:08.000'; %TLE Epoch 
GMAT ISS.CoordinateSystem = EarthFixed;
GMAT ISS.DisplayStateType = Cartesian;

GMAT ISS.EphemerisName = 'C:\Users\Utente\Downloads\Progettino\TLE_ISS.txt';
GMAT ISS.Id = '25544U';


% Modello terrestre

Create ForceModel FM;
GMAT FM.CentralBody = Earth;
GMAT FM.PrimaryBodies = {Earth};


% Propagatore (scelto SPICESGP4 perche uso i TLE)

Create Propagator Prop;
GMAT Prop.Type = SPICESGP4;
GMAT Prop.FM = FM;


% Creazione del report file

Create ReportFile ReportFile1;

GMAT ReportFile1.Filename = 'C:\Users\Utente\Downloads\Progettino\IssMATLAB.txt';
GMAT ReportFile1.WriteHeaders = true;
GMAT ReportFile1.FixedWidth = false;


% Mission sequence

BeginMissionSequence;

While ISS.ElapsedDays < 3

   Report ReportFile1 ISS.UTCGregorian ISS.EarthFixed.X ISS.EarthFixed.Y ISS.EarthFixed.Z ISS.Earth.Latitude ISS.Earth.Longitude ISS.ElapsedSecs;

   Propagate Prop(ISS) {ISS.ElapsedSecs = 10};

EndWhile;